development:
  adapter: redis
  url: redis://<%= ENV['REDIS_HOST'] %>:6379/1
  channel_prefix: myapp_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:8de83c34556f32a902a06c5aeb538c43@angelfish.redistogo.com:11260/
  channel_prefix: myapp_production
